name: Compile and Run

on:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Compile main.src
        run: |
          g++ g++ -O0 -std=c++17 -Wall -Wextra -Wpedantic -Wuninitialized -fno-strict-aliasing -fwrapv -g3 -o main main.cpp

      - name: Run the compiled program
        run: |
          ./main

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: program-output
          path: |
            main
